# seo
title: "gohu blog"
description: "anything"
url: "https://blog.gohu.dev"
author: "GOHU"

# path
baseurl: "/"
permalink: /:categories/:title
collections_dir: collections
collections:
  develop:
    output: true
    permalink: /:categories/:title
  algorithm:
    output: true
    permalink: /:categories/:title
  math: 
    output: true
    permalink: /:categories/:title
  language:
    output: true
    permalink: /:categories/:title
defaults:
  - scope: # Post
      path: collections/_posts
    values:
      layout: post
      permalink: /post/:categories/:title
  - scope: # Algorithm
      path: collections/_algorithm
      type: algorithm
    values:
      categories:
        - algorithm
  - scope: # Hardware
      path: collections/_hardware
      type: hardware
    values:
      categories:
        - hardware
  - scope: # CPU
      path: collections/_hardware/cpu
    values:
      categories:
        - hardware
        - cpu
  - scope: # GPU
      path: collections/_hardware/gpu
    values:
      categories:
        - hardware
        - gpu
  - scope: # RAM
      path: collections/_hardware/ram
    values:
      categories:
        - hardware
        - ram
  - scope: # Math
      path: collections/_math
      type: math
    values:
      categories:
        - math
  - scope: # English
      path: collections/_language/english
    values:
      categories:
        - english
  - scope: # Windows
      path: collections/_develop/os/windows
    values:
      categories:
        - os
        - windows
  - scope: # Linux
      path: collections/_develop/os/linux
    values:
      categories:
        - os
        - linux
  - scope: # Android
      path: collections/_develop/os/android
    values:
      categories:
        - os
        - android
  - scope: # HTML
      path: collections/_develop/web/html
    values:
      categories:
        - html
  - scope: # CSS
      path: collections/_develop/web/css
    values:
      categories:
        - css
  - scope: # SCSS
      path: collections/_develop/web/scss
    values:
      categories:
        - scss
  - scope: # WGSL
      path: collections/_develop/web/wgsl
    values:
      categories:
        - wgsl
  - scope: # liquid
      path: collections/_develop/web/template/liquid
    values:
      categories:
        - liquid
  - scope: # C
      path: collections/_develop/language/clang
    values:
      categories:
        - clang
  - scope: # C++
      path: collections/_develop/language/c++
    values:
      categories:
        - c++
  - scope: # Python
      path: collections/_develop/language/python
    values:
      categories:
        - python
  - scope: # Rust
      path: collections/_develop/language/rust
    values:
      categories:
        - rust
  - scope: # Javascript
      path: collections/_develop/language/javascript
    values:
      categories:
        - javascript
  - scope: # Typescript
      path: collections/_develop/language/typescript
    values:
      categories:
        - typescript
  - scope: # React
      path: collections/_develop/library/react
    values:
      categories:
        - react
  - scope: # Jekyll
      path: collections/_develop/framework/jekyll
    values:
      categories:
        - jekyll
  - scope: # Cloud
      path: collections/_develop/cloud
    values:
      categories:
        - cloud
  - scope: # AWS
      path: collections/_develop/cloud/aws
    values:
      categories:
        - cloud
        - aws
  - scope: # Azure
      path: collections/_develop/cloud/azure
    values:
      categories:
        - cloud
        - azure
  - scope: # git
      path: collections/_develop/tool/git
    values:
      categories:
        - git
  - scope: # vscode
      path: collections/_develop/tool/vscode
    values:
      categories:
        - vscode
  - scope: # vscode
      path: collections/_develop/tool/vscode/extension
    values:
      categories:
        - vscode
        - extension
  


# markdown
markdown: CommonMarkGhPages
commonmark:
  options: 
    - SMART
    - FOOTNOTES
  extensions: 
    - strikethrough
    - autolink
    - table
    - tagfilter
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-avatar
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-redirect-from
  - jekyll-sass-converter
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jemoji