# seo
title: "gohu blog"
description: "anything"
url: "https://blog.gohu.dev"
author: "GOHU"

# path
baseurl: "/"
permalink: /:categories/:title
collections_dir: collections
collections:
  theory:
    output: true
  develop:
    output: true
  language:
    output: true
  quiz:
    output: true
defaults:
  - scope: # post
      path: collections/_posts 
      type: posts
    values:
      permalink: post/:categories/:title
      layout: post
  - scope: # theory
      path: collections/_theory/
      type: theory
    values:
      permalink: /theory/:categories/:name
      layout: post
  - scope: # develop
      path: collections/_develop
      type: develop
    values:
      permalink: /develop/:categories/:name
      layout: post
  - scope: # language
      path: collections/_language
      type: language
    values:
      permalink: /language/:categories/:name
      layout: post
  - scope: # C
      path: collections/_develop/language/clang
      type: develop
    values:
      categories: 
        - clang
  - scope: # C++
      path: collections/_develop/language/c++
      type: develop
    values:
      categories: 
        - c++
  - scope: # Python
      path: collections/_develop/language/python
      type: develop
    values:
      categories: 
        - python
  - scope: # Rust
      path: collections/_develop/language/rust
      type: develop
    values:
      categories: 
        - rust
  - scope: # React
      path: collections/_develop/library/react
      type: develop
    values:
      categories: 
        - react
  - scope: # vscode
      path: collections/_develop/tools/vscode
      type: develop
    values:
      categories: 
        - vscode
  - scope: # vscode/extension
      path: collections/_develop/tools/vscode/extension
      type: develop
    values:
      categories: 
        - vscode
        - extension
  - scope: # data structure
      path: collections/_theory/computer/data-structure
      type: theory
    values:
      categories: 
        - data-structure
  - scope: # algorithm
      path: collections/_theory/computer/algorithm
      type: theory
    values:
      categories: 
        - algorithm
  - scope: # cpu
      path: collections/_theory/computer/hardware/cpu
      type: theory
    values:
      categories: 
        - cpu
  - scope: # gpu
      path: collections/_theory/computer/hardware/gpu
      type: theory
    values:
      categories: 
        - gpu
  - scope: # RAM
      path: collections/_theory/computer/hardware/ram
      type: theory
    values:
      categories: 
        - ram
  - scope: # cloud
      path: collections/_theory/develop/cloud
      type: theory
    values:
      categories: 
        - cloud
  - scope: # math
      path: collections/_theory/math
      type: theory
    values:
      categories: 
        - math
      components: 
        - math
  - scope:
      path: collections/_language/english
      type: language
    values:
      categories:
        - english

# markdown
markdown: CommonMarkGhPages
commonmark:
  options: 
    - SMART
    - FOOTNOTES
  extensions: 
    - strikethrough
    - autolink
    - table
    - tagfilter
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-avatar
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-redirect-from
  - jekyll-sass-converter
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jemoji